{
 "title": "9112 - PowerDNS",
 "description": "Prometheus Powerdns exporter metrics.",
 "tags": [
  "prometheus",
  "powerdns"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "label": "database", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job=~\"pdns_exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "All outqueries $instance",
   "type": "graph",
   "description": "Number of outgoing UDP queries since starting",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_all_outqueries{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "All IPv6 outqueries $instance",
   "type": "graph",
   "description": "Number of outgoing queries via IPv6 since starting",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_ipv6_outqueries{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{$instance}"
    }
   ]
  },
  {
   "title": "Questions $instance",
   "type": "graph",
   "description": "counts all end-user initiated queries with the RD bit set",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_questions{instance=~\"$instance\"}[1m]) + rate(pdns_recursor_ipv6_questions{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Answers $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_answers0_1{instance=~\"$instance\"}[1m]))",
     "legendFormat": "0-1 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_answers1_10{instance=~\"$instance\"}[1m]))",
     "legendFormat": "1-10 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_answers10_100{instance=~\"$instance\"}[1m]))",
     "legendFormat": "10-100 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_answers100_1000{instance=~\"$instance\"}[1m]))",
     "legendFormat": "100-1000 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_answers_slow{instance=~\"$instance\"}[1m]))",
     "legendFormat": "slow"
    }
   ]
  },
  {
   "title": "Answers auth4 $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_auth4_answers0_1{instance=~\"$instance\"}[1m]))",
     "legendFormat": "0-1 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth4_answers1_10{nstance=~\"$instance\"}[1m]))",
     "legendFormat": "1-10 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth4_answers10_100{instance=~\"$instance\"}[1m]))",
     "legendFormat": "10-100 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth4_answers100_1000{instance=~\"$instance\"}[1m]))",
     "legendFormat": "100-1000 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth4_answers_slow{instance=~\"$instance\"}[1m]))",
     "legendFormat": "slow"
    }
   ]
  },
  {
   "title": "Answers auth6 $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_auth6_answers0_1{instance=~\"$instance\"}[1m]))",
     "legendFormat": "0-1 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth6_answers1_10{instance=~\"$instance\"}[1m]))",
     "legendFormat": "1-10 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth6_answers10_100{instance=~\"$instance\"}[1m]))",
     "legendFormat": "10-100 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth6_answers100_1000{instance=~\"$instance\"}[1m]))",
     "legendFormat": "100-1000 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth6_answers_slow{instance=~\"$instance\"}[1m]))",
     "legendFormat": "slow"
    }
   ]
  },
  {
   "title": "Cache $instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_cache_hits{nstance=~\"$instance\"}[1m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum (rate(pdns_recursor_cache_misses{instance=~\"$instance\"}[1m]))",
     "legendFormat": "misses"
    },
    {
     "expr": "sum (rate(pdns_recursor_cache_entries{instance=~\"$instance\"}[1m]))",
     "legendFormat": "entries"
    },
    {
     "expr": "sum (rate(pdns_recursor_negcache_entries{instance=~\"$instance\"}[1m]))",
     "legendFormat": "negative"
    }
   ]
  },
  {
   "title": "Failed events $instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_servfail_answers{instance=~\"$instance\"}[1m]))",
     "legendFormat": "SERVFAIL"
    },
    {
     "expr": "sum (rate(pdns_recursor_nxdomain_answers{instance=~\"$instance\"}[1m]))",
     "legendFormat": "NXDomain"
    },
    {
     "expr": "sum (rate(pdns_recursor_failed_host_entries{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Failed host"
    },
    {
     "expr": "sum (rate(pdns_recursor_unauthorized_udp{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Unauthorized UDP"
    },
    {
     "expr": "sum (rate(pdns_recursor_outgoing_timeouts{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum (rate(pdns_recursor_policy_result_noaction{instance=~\"$instance\"}[1m]))",
     "legendFormat": "No action"
    }
   ]
  },
  {
   "title": "CPU msec $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_cpu_msec_thread_0{instance=~\"$instance\"}[1m]))",
     "legendFormat": "CPU thread 0"
    },
    {
     "expr": "sum (rate(pdns_recursor_cpu_msec_thread_1{instance=~\"$instance\"}[1m]))",
     "legendFormat": "CPU thread 1"
    },
    {
     "expr": "sum (rate(pdns_recursor_cpu_msec_thread_2{instance=~\"$instance\"}[1m]))",
     "legendFormat": "CPU thread 2"
    },
    {
     "expr": "sum (rate(pdns_recursor_sys_msec{instance=~\"$instance\"}[1m]))",
     "legendFormat": "System mode"
    },
    {
     "expr": "sum (rate(pdns_recursor_user_msec{instance=~\"$instance\"}[1m]))",
     "legendFormat": "User mode"
    }
   ]
  },
  {
   "title": "DNSSEC $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_dnssec_queries{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Querries"
    },
    {
     "expr": "sum (rate(pdns_recursor_dnssec_check_disabled_queries{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Querries check disabled"
    }
   ]
  }
 ]
}