name: ansible-observability

networks:
  servers-net:
    name: docker-servers-net
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      servers-net:
        ipv4_address: 192.168.59.20
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=[REDACTED]
    networks:
      servers-net:
        ipv4_address: 192.168.59.21
    restart: unless-stopped
