name: ollama

networks:
  rproxy:
    name: rproxy
    external: true

volumes:
  ollama:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/nfs/dockermaster/volumes/ollama.ollama'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    hostname: ollama-server
    networks:
      rproxy:
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      com.docker.stack: "ollama"
      com.docker.service: "ollama"
      portainer.autodeploy: "false"
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 42G
        reservations:
          cpus: '0.25'
          memory: 256M
