name: [SERVICE_NAME]

networks:
  servers-net:
    name: docker-servers-net
    driver: macvlan
    external: true

services:
  [service]:
    image: [IMAGE:TAG]
    container_name: [CONTAINER_NAME]
    hostname: [HOSTNAME]
    restart: unless-stopped
    
    # Environment configuration
    environment:
      - VARIABLE_NAME=value
    # Or use env_file for sensitive data
    # env_file: .env
    
    # Network configuration
    networks:
      servers-net:
        ipv4_address: 192.168.59.X
    
    # Port exposure (use expose for internal, ports for external)
    expose:
      - PORT
    # ports:
    #   - "HOST_PORT:CONTAINER_PORT"
    
    # Volume mounts
    volumes:
      - service_data:/data
      - service_config:/config
      - /host/path:/container/path
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:PORT/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Dependencies
    # depends_on:
    #   - other_service
    
    # Resource limits
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #       cpus: '0.5'

# Volume definitions
volumes:
  service_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/nfs/dockermaster/volumes/[service-name].data'
  
  service_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/nfs/dockermaster/volumes/[service-name].config'