name: la-RunDeck

networks:
  servers-net:
    name: docker-servers-net
    driver: macvlan
    external: true

services:
  rundeck:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - rundeck:local
    container_name: rundeck
    hostname: rundeck-local
    environment:
      RUNDECK_SERVER_UUID: 2356DEE1-1A12-463C-8ABB-D6A9F44161B4
      RUNDECK_DATABASE_DRIVER: org.postgresql.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: "${RUNDECK_DATABASE_PASSWORD}"
      RUNDECK_DATABASE_URL: jdbc:postgresql://postgres/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      RUNDECK_GRAILS_URL: http://rundeck.d.lcamaral.com
      RUNDECK_SERVER_FORWARDED: true
      RUNDECK_STORAGE_CONVERTER_1_CONFIG_PASSWORD: "${RUNDECK_STORAGE_PASSWORD}"
      RUNDECK_CONFIG_STORAGE_CONVERTER_1_CONFIG_PASSWORD: "${RUNDECK_CONFIG_STORAGE_PASSWORD}"
      RUNDECK_PASSWORD_RESET_ENABLED: true
    restart: always
    expose:
      - 4440
    networks:
      servers-net:
        ipv4_address: 192.168.59.22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /nfs/dockermaster/docker/rundeck/data:/home/rundeck/server/data
      - /nfs/dockermaster/docker/rundeck/container-plugins:/home/rundeck/container-plugins
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-rundeck
    hostname: postgres
    networks:
      servers-net:
        ipv4_address: 192.168.59.23
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=rundeck
      - POSTGRES_USER=rundeck
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /nfs/dockermaster/docker/rundeck/dbdata:/var/lib/postgresql/data
