name: la-RunDeck

networks:
  servers-net:
    name: docker-servers-net
    driver: macvlan
    external: true

services:
  rundeck:
    # Using official Rundeck image from Docker Hub
    # Migration from local build to registry-based deployment
    image: rundeck/rundeck:5.8.0
    container_name: rundeck
    hostname: rundeck-local
    environment:
      RUNDECK_SERVER_UUID: 2356DEE1-1A12-463C-8ABB-D6A9F44161B4
      RUNDECK_DATABASE_DRIVER: org.postgresql.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: ${RUNDECK_DB_PASSWORD}
      RUNDECK_DATABASE_URL: jdbc:postgresql://postgres/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      RUNDECK_GRAILS_URL: http://rundeck.d.lcamaral.com
      RUNDECK_SERVER_FORWARDED: true
      RUNDECK_STORAGE_CONVERTER_1_CONFIG_PASSWORD: ${RUNDECK_STORAGE_PASSWORD}
      RUNDECK_CONFIG_STORAGE_CONVERTER_1_CONFIG_PASSWORD: ${RUNDECK_CONFIG_PASSWORD}
      RUNDECK_PASSWORD_RESET_ENABLED: true
    restart: always
    expose:
      - 4440
    networks:
      servers-net:
        ipv4_address: 192.168.59.22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /nfs/dockermaster/docker/rundeck/data:/home/rundeck/server/data
      - /nfs/dockermaster/docker/rundeck/container-plugins:/home/rundeck/container-plugins
    depends_on:
      - postgres
    labels:
      # Watchtower labels for automatic updates
      com.centurylinklabs.watchtower.enable: "true"
      com.centurylinklabs.watchtower.monitor-only: "false"

  postgres:
    image: postgres:16-alpine
    container_name: postgres-rundeck
    hostname: postgres
    networks:
      servers-net:
        ipv4_address: 192.168.59.23
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=rundeck
      - POSTGRES_USER=rundeck
      - POSTGRES_PASSWORD=${RUNDECK_DB_PASSWORD}
    volumes:
      - /nfs/dockermaster/docker/rundeck/dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rundeck"]
      interval: 30s
      timeout: 10s
      retries: 3
