name: bind-dns

networks:
  servers-net:
    name: docker-servers-net
    external: true

services:
  bind9:
    image: ubuntu/bind9:9.20-24.10_edge
    networks:
      servers-net:
        ipv4_address: 192.168.59.3
    environment:
      - BIND9_USER=root
      - TZ=America/Denver
    volumes:
      - /nfs/dockermaster/docker/bind9/config:/etc/bind
      - /nfs/dockermaster/docker/bind9/cache:/var/cache/bind
      - /nfs/dockermaster/docker/bind9/records:/var/lib/bind
    restart: always
    healthcheck:
      test: ["CMD", "sh", "-c", "ss -uln | grep -q :53"]
      interval: 5s
      timeout: 5s
      retries: 15
    labels:
      loki.logging: "true"
      com.centurylinklabs.watchtower.enable: "false"
      com.docker.stack: "bind9"
      com.docker.service: "bind9"
      portainer.autodeploy: "false"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
