name: calibre

networks:
  rproxy:
    name: rproxy
    external: true

services:
  calibre:
    image: linuxserver/calibre:latest
    hostname: calibre
    container_name: calibre
    shm_size: '2gb'
    networks:
      rproxy:
    ports:
      - 58090:9090
    volumes:
      - /nfs/calibre/Library:/Library
      - /nfs/calibre/config:/config
      - /nfs/calibre/upload:/upload
      - /nfs/calibre/plugins:/plugins
      - /nfs/dockermaster/docker/calibre-server/10-keyboard.conf:/etc/X11/xorg.conf.d/10-keyboard.conf
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp:unconfined
    environment:
      PUID: 1027
      PGID: 65539
      CUSTOM_USER: 'admin'
      PASSWORD: ${CALIBRE_PASSWORD}
      TZ: 'America/Denver'
      DISABLE_IPV6: true
      LANG: en_US.UTF-8
    restart: always
    labels:
      com.lcamaral.home.watchtower.enable: "false"  # Manual updates only
      com.docker.stack: "calibre"
      com.docker.service: "calibre"
      portainer.autodeploy: "false"

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    hostname: calibre-web
    networks:
      rproxy:
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /nfs/calibre/calibre-web/config:/config
      - /nfs/calibre/calibre-web/Library:/books
    restart: unless-stopped
    labels:
      com.lcamaral.home.watchtower.enable: "false"
      com.docker.stack: "calibre"
      com.docker.service: "calibre-web"
      portainer.autodeploy: "false"
