name: keycloak

networks:
  servers-net:
    name: docker-servers-net
    external: true
  keycloak-internal:

services:
  keycloak:
    image: keycloak/keycloak:26.3
    container_name: keycloak
    hostname: keycloak
    command: start
    networks:
      servers-net:
        ipv4_address: 192.168.59.13
      keycloak-internal:
    environment:
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8080'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
    depends_on:
      keycloak-db:
        condition: service_healthy
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      com.docker.stack: "keycloak"
      com.docker.service: "keycloak"
      portainer.autodeploy: "false"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1250M

  keycloak-db:
    image: postgres:17
    container_name: keycloak-db
    hostname: keycloak-db
    networks:
      keycloak-internal:
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /nfs/dockermaster/docker/keycloak/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak", "-d", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      com.docker.stack: "keycloak"
      com.docker.service: "keycloak-db"
      portainer.autodeploy: "false"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
