name: Runner Strategy

on:
  workflow_call:
    inputs:
      prefer-self-hosted:
        description: 'Prefer self-hosted runner when available'
        required: false
        type: boolean
        default: true
      runner-labels:
        description: 'Additional runner labels'
        required: false
        type: string
        default: ''
    outputs:
      runner:
        description: 'Selected runner configuration'
        value: ${{ jobs.select-runner.outputs.runner }}

jobs:
  select-runner:
    name: Select Runner
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.select.outputs.runner }}
    steps:
      - name: Check self-hosted runner availability
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: runners } = await github.rest.actions.listSelfHostedRunnersForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const dockermasterRunner = runners.runners.find(r => 
                r.labels.some(l => l.name === 'dockermaster') && 
                r.status === 'online'
              );
              
              if (dockermasterRunner) {
                core.setOutput('available', 'true');
                core.setOutput('runner_name', dockermasterRunner.name);
                console.log(`Self-hosted runner available: ${dockermasterRunner.name}`);
              } else {
                core.setOutput('available', 'false');
                console.log('No self-hosted runner available');
              }
            } catch (error) {
              core.setOutput('available', 'false');
              console.log('Error checking runners:', error.message);
            }
      
      - name: Select runner configuration
        id: select
        run: |
          if [[ "${{ inputs.prefer-self-hosted }}" == "true" ]] && [[ "${{ steps.check.outputs.available }}" == "true" ]]; then
            echo "runner=['self-hosted', 'dockermaster']" >> $GITHUB_OUTPUT
            echo "Selected self-hosted runner"
          else
            echo "runner='ubuntu-latest'" >> $GITHUB_OUTPUT
            echo "Selected GitHub-hosted runner"
          fi